### ISSUE TITLE
Integrate black in the CI

### ISSUE THREAD

**Issue by vineetbansal** [walruscorp/walrus#10]
To enforce that all developers of `walrus` stick to the same formatting conventions, we talked about using `black` locally earlier. There's got to be a mode in `black` where it simply tells us what, if anything, it would have reformatted and returns an appropriate zero/non-zero return code. We should integrate this check in the CI (before the expensive `pytest` step).

**Comment by anushka255** [comment]
Integrated black on CI using two black commands - "black ." followed by "black --check .". The check option doesn't write the file back but just returns the status. Return code 0 means nothing would change and return code 1 means some files would be reformatted.

**Comment by vineetbansal** [comment]
Great! I don't see a PR on that but you can submit it when ready.

One thing we may want to do is to pin down the version of `black` (to whatever is current right now) in our dev dependencies so that any future versions of `black` that may make different formatting choices don't end up complaining and invalidating our code (we just care if the code is formatted according to *some* convention, not necessarily what the `black` team considers the best convention at any point of time).

This pinning down of dev dependencies doesn't really hold for `flake8` or `pyright`, since presumably, any changes they make to their recommendations would be only to improve typical developer experience, not arbitrarily change it, so we can leave those versions floating.

**Comment by anushka255** [comment]
Pinned down the version of black on pyproject.toml.

**Comment by vineetbansal** [comment]
Thanks!
